import type { EligibleFactoryCandidateDTO } from './eligible-factories.types';

export const MOCK_ELIGIBLE_FACTORY_CANDIDATES: EligibleFactoryCandidateDTO[] = [
  {
    sourceSystem: 'mock_external_factory_db',
    sourceFactoryId: 'mock-factory-0001',
    factoryName: 'บริษัท สมุทรรีไซเคิล จำกัด',
    factoryRegistrationNoNew: '3-101-10/66สป',
    factoryRegistrationNoOld: 'รง.4-10001',
    factoryTypeSequence: 'หลัก',
    address: '88 หมู่ 2 ถนนปู่เจ้าสมิงพราย',
    provinceName: 'สมุทรปราการ',
    industrialEstateName: 'นิคมอุตสาหกรรมบางปู',
    coordinates: { latitude: 13.5432181, longitude: 100.6329124 },
    businessActivity: 'หลอมและรีไซเคิลโลหะ',
    operationStatus: 'แจ้งประกอบแล้ว',
    capitalAmount: 15000000,
    machineryHorsepower: 540,
    productionCapacity: '80 ตัน/วัน',
    wastewaterDischargeInfo: 'มีการระบายน้ำทิ้งออกนอกโรงงาน',
    boilerCount: 1,
    boilerSizeEach: '8 ตัน/ชั่วโมง',
    fuelUsed: 'ก๊าซธรรมชาติ',
    hasEia: true,
  },
  {
    sourceSystem: 'mock_external_factory_db',
    sourceFactoryId: 'mock-factory-0002',
    factoryName: 'บริษัท เจ้าพระยาเคมีคอล จำกัด',
    factoryRegistrationNoNew: '3-042-21/65อย',
    factoryRegistrationNoOld: 'รง.4-10002',
    factoryTypeSequence: 'หลัก',
    address: '12 หมู่ 5 ถนนโรจนะ',
    provinceName: 'พระนครศรีอยุธยา',
    industrialEstateName: 'นิคมอุตสาหกรรมโรจนะ',
    coordinates: { latitude: 14.3234412, longitude: 100.6412271 },
    businessActivity: 'ผลิตสารเคมีสำหรับอุตสาหกรรม',
    operationStatus: 'แจ้งประกอบแล้ว',
    capitalAmount: 28000000,
    machineryHorsepower: 920,
    productionCapacity: '120 ตัน/วัน',
    wastewaterDischargeInfo: 'มีระบบบำบัดและระบายน้ำทิ้งออกนอกโรงงาน',
    boilerCount: 2,
    boilerSizeEach: '12 ตัน/ชั่วโมง',
    fuelUsed: 'น้ำมันเตา',
    hasEia: true,
  },
  {
    sourceSystem: 'mock_external_factory_db',
    sourceFactoryId: 'mock-factory-0003',
    factoryName: 'บริษัท อีสเทิร์นฟู้ดโปรเซสซิ่ง จำกัด',
    factoryRegistrationNoNew: '3-088-45/64ชบ',
    factoryRegistrationNoOld: 'รง.4-10003',
    factoryTypeSequence: 'รอง',
    address: '199 หมู่ 7',
    provinceName: 'ชลบุรี',
    industrialEstateName: 'นิคมอุตสาหกรรมอมตะซิตี้ ชลบุรี',
    coordinates: { latitude: 13.4067824, longitude: 101.0314567 },
    businessActivity: 'แปรรูปอาหารทะเลแช่แข็ง',
    operationStatus: 'แจ้งประกอบแล้ว',
    capitalAmount: 9500000,
    machineryHorsepower: 310,
    productionCapacity: '35 ตัน/วัน',
    wastewaterDischargeInfo: 'มีน้ำเสียจากกระบวนการผลิต',
    boilerCount: 1,
    boilerSizeEach: '5 ตัน/ชั่วโมง',
    fuelUsed: 'ชีวมวล',
    hasEia: false,
  },
  {
    sourceSystem: 'mock_external_factory_db',
    sourceFactoryId: 'mock-factory-0004',
    factoryName: 'ห้างหุ้นส่วนจำกัด นครพลาสติก',
    factoryRegistrationNoNew: '3-053-12/63นฐ',
    factoryRegistrationNoOld: 'รง.4-10004',
    factoryTypeSequence: 'หลัก',
    address: '45/9 ถนนเพชรเกษม',
    provinceName: 'นครปฐม',
    industrialEstateName: null,
    coordinates: { latitude: 13.8197211, longitude: 100.0611923 },
    businessActivity: 'ผลิตบรรจุภัณฑ์พลาสติก',
    operationStatus: 'แจ้งประกอบแล้ว',
    capitalAmount: 4200000,
    machineryHorsepower: 180,
    productionCapacity: '12 ตัน/วัน',
    wastewaterDischargeInfo: 'ไม่มีการระบายน้ำทิ้งจากกระบวนการผลิต',
    boilerCount: 0,
    boilerSizeEach: null,
    fuelUsed: 'ไฟฟ้า',
    hasEia: false,
  },
  {
    sourceSystem: 'mock_external_factory_db',
    sourceFactoryId: 'mock-factory-0005',
    factoryName: 'บริษัท ระยองพาวเวอร์บอยเลอร์ จำกัด',
    factoryRegistrationNoNew: '3-106-33/50รย',
    factoryRegistrationNoOld: 'รง.4-10005',
    factoryTypeSequence: 'หลัก',
    address: '7 ถนนไอ-หนึ่ง',
    provinceName: 'ระยอง',
    industrialEstateName: 'นิคมอุตสาหกรรมมาบตาพุด',
    coordinates: { latitude: 12.6819444, longitude: 101.1538888 },
    businessActivity: 'ผลิตไอน้ำและพลังงานความร้อน',
    operationStatus: 'แจ้งประกอบแล้ว',
    capitalAmount: 50000000,
    machineryHorsepower: 1500,
    productionCapacity: '250 ตันไอน้ำ/วัน',
    wastewaterDischargeInfo: 'มีการระบายน้ำหล่อเย็นและน้ำทิ้ง',
    boilerCount: 4,
    boilerSizeEach: '25 ตัน/ชั่วโมง',
    fuelUsed: 'ก๊าซธรรมชาติ',
    hasEia: true,
  },
  {
    sourceSystem: 'mock_external_factory_db',
    sourceFactoryId: 'mock-factory-0006',
    factoryName: 'บริษัท ลำพูนอิเล็กทรอนิกส์ จำกัด',
    factoryRegistrationNoNew: '3-072-09/62ลพ',
    factoryRegistrationNoOld: 'รง.4-10006',
    factoryTypeSequence: 'รอง',
    address: '60 หมู่ 4',
    provinceName: 'ลำพูน',
    industrialEstateName: 'นิคมอุตสาหกรรมภาคเหนือ',
    coordinates: { latitude: 18.5799821, longitude: 99.0162742 },
    businessActivity: 'ประกอบชิ้นส่วนอิเล็กทรอนิกส์',
    operationStatus: 'หยุดประกอบกิจการชั่วคราว',
    capitalAmount: 18000000,
    machineryHorsepower: 260,
    productionCapacity: '50000 ชิ้น/วัน',
    wastewaterDischargeInfo: 'มีน้ำเสียจากการล้างชิ้นงาน',
    boilerCount: 0,
    boilerSizeEach: null,
    fuelUsed: 'ไฟฟ้า',
    hasEia: false,
  },
];
