import type { Knex } from 'knex';

const PROVINCES = [
  { id: '1000', name_th: 'กรุงเทพมหานคร', name_en: 'Bangkok', region: 'ภาคกลาง' },
  { id: '1011', name_th: 'สมุทรปราการ', name_en: 'Samut Prakan', region: 'ภาคกลาง' },
  { id: '1012', name_th: 'นนทบุรี', name_en: 'Nonthaburi', region: 'ภาคกลาง' },
  { id: '1013', name_th: 'ปทุมธานี', name_en: 'Pathum Thani', region: 'ภาคกลาง' },
  { id: '1014', name_th: 'พระนครศรีอยุธยา', name_en: 'Phra Nakhon Si Ayutthaya', region: 'ภาคกลาง' },
  { id: '1015', name_th: 'อ่างทอง', name_en: 'Ang Thong', region: 'ภาคกลาง' },
  { id: '1016', name_th: 'ลพบุรี', name_en: 'Lop Buri', region: 'ภาคกลาง' },
  { id: '1017', name_th: 'สิงห์บุรี', name_en: 'Sing Buri', region: 'ภาคกลาง' },
  { id: '1018', name_th: 'ชัยนาท', name_en: 'Chai Nat', region: 'ภาคกลาง' },
  { id: '1019', name_th: 'สระบุรี', name_en: 'Saraburi', region: 'ภาคกลาง' },
  { id: '1020', name_th: 'ชลบุรี', name_en: 'Chon Buri', region: 'ภาคตะวันออก' },
  { id: '1021', name_th: 'ระยอง', name_en: 'Rayong', region: 'ภาคตะวันออก' },
  { id: '1022', name_th: 'จันทบุรี', name_en: 'Chanthaburi', region: 'ภาคตะวันออก' },
  { id: '1023', name_th: 'ตราด', name_en: 'Trat', region: 'ภาคตะวันออก' },
  { id: '1024', name_th: 'ฉะเชิงเทรา', name_en: 'Chachoengsao', region: 'ภาคตะวันออก' },
  { id: '1025', name_th: 'ปราจีนบุรี', name_en: 'Prachin Buri', region: 'ภาคตะวันออก' },
  { id: '1026', name_th: 'นครนายก', name_en: 'Nakhon Nayok', region: 'ภาคกลาง' },
  { id: '1027', name_th: 'สระแก้ว', name_en: 'Sa Kaeo', region: 'ภาคตะวันออก' },
  { id: '1030', name_th: 'นครราชสีมา', name_en: 'Nakhon Ratchasima', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1031', name_th: 'บุรีรัมย์', name_en: 'Buri Ram', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1032', name_th: 'สุรินทร์', name_en: 'Surin', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1033', name_th: 'ศรีสะเกษ', name_en: 'Si Sa Ket', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1034', name_th: 'อุบลราชธานี', name_en: 'Ubon Ratchathani', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1035', name_th: 'ยโสธร', name_en: 'Yasothon', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1036', name_th: 'ชัยภูมิ', name_en: 'Chaiyaphum', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1037', name_th: 'อำนาจเจริญ', name_en: 'Amnat Charoen', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1038', name_th: 'บึงกาฬ', name_en: 'Bueng Kan', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1039', name_th: 'หนองบัวลำภู', name_en: 'Nong Bua Lamphu', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1040', name_th: 'ขอนแก่น', name_en: 'Khon Kaen', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1041', name_th: 'อุดรธานี', name_en: 'Udon Thani', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1042', name_th: 'เลย', name_en: 'Loei', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1043', name_th: 'หนองคาย', name_en: 'Nong Khai', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1044', name_th: 'มหาสารคาม', name_en: 'Maha Sarakham', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1045', name_th: 'ร้อยเอ็ด', name_en: 'Roi Et', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1046', name_th: 'กาฬสินธุ์', name_en: 'Kalasin', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1047', name_th: 'สกลนคร', name_en: 'Sakon Nakhon', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1048', name_th: 'นครพนม', name_en: 'Nakhon Phanom', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1049', name_th: 'มุกดาหาร', name_en: 'Mukdahan', region: 'ภาคตะวันออกเฉียงเหนือ' },
  { id: '1050', name_th: 'เชียงใหม่', name_en: 'Chiang Mai', region: 'ภาคเหนือ' },
  { id: '1051', name_th: 'ลำพูน', name_en: 'Lamphun', region: 'ภาคเหนือ' },
  { id: '1052', name_th: 'ลำปาง', name_en: 'Lampang', region: 'ภาคเหนือ' },
  { id: '1053', name_th: 'อุตรดิตถ์', name_en: 'Uttaradit', region: 'ภาคเหนือ' },
  { id: '1054', name_th: 'แพร่', name_en: 'Phrae', region: 'ภาคเหนือ' },
  { id: '1055', name_th: 'น่าน', name_en: 'Nan', region: 'ภาคเหนือ' },
  { id: '1056', name_th: 'พะเยา', name_en: 'Phayao', region: 'ภาคเหนือ' },
  { id: '1057', name_th: 'เชียงราย', name_en: 'Chiang Rai', region: 'ภาคเหนือ' },
  { id: '1058', name_th: 'แม่ฮ่องสอน', name_en: 'Mae Hong Son', region: 'ภาคเหนือ' },
  { id: '1060', name_th: 'นครสวรรค์', name_en: 'Nakhon Sawan', region: 'ภาคกลาง' },
  { id: '1061', name_th: 'อุทัยธานี', name_en: 'Uthai Thani', region: 'ภาคกลาง' },
  { id: '1062', name_th: 'กำแพงเพชร', name_en: 'Kamphaeng Phet', region: 'ภาคกลาง' },
  { id: '1063', name_th: 'ตาก', name_en: 'Tak', region: 'ภาคตะวันตก' },
  { id: '1064', name_th: 'สุโขทัย', name_en: 'Sukhothai', region: 'ภาคเหนือ' },
  { id: '1065', name_th: 'พิษณุโลก', name_en: 'Phitsanulok', region: 'ภาคเหนือ' },
  { id: '1066', name_th: 'พิจิตร', name_en: 'Phichit', region: 'ภาคเหนือ' },
  { id: '1067', name_th: 'เพชรบูรณ์', name_en: 'Phetchabun', region: 'ภาคเหนือ' },
  { id: '1070', name_th: 'ราชบุรี', name_en: 'Ratchaburi', region: 'ภาคตะวันตก' },
  { id: '1071', name_th: 'กาญจนบุรี', name_en: 'Kanchanaburi', region: 'ภาคตะวันตก' },
  { id: '1072', name_th: 'สุพรรณบุรี', name_en: 'Suphan Buri', region: 'ภาคกลาง' },
  { id: '1073', name_th: 'นครปฐม', name_en: 'Nakhon Pathom', region: 'ภาคกลาง' },
  { id: '1074', name_th: 'สมุทรสาคร', name_en: 'Samut Sakhon', region: 'ภาคกลาง' },
  { id: '1075', name_th: 'สมุทรสงคราม', name_en: 'Samut Songkhram', region: 'ภาคกลาง' },
  { id: '1076', name_th: 'เพชรบุรี', name_en: 'Phetchaburi', region: 'ภาคตะวันตก' },
  { id: '1077', name_th: 'ประจวบคีรีขันธ์', name_en: 'Prachuap Khiri Khan', region: 'ภาคตะวันตก' },
  { id: '1080', name_th: 'นครศรีธรรมราช', name_en: 'Nakhon Si Thammarat', region: 'ภาคใต้' },
  { id: '1081', name_th: 'กระบี่', name_en: 'Krabi', region: 'ภาคใต้' },
  { id: '1082', name_th: 'พังงา', name_en: 'Phangnga', region: 'ภาคใต้' },
  { id: '1083', name_th: 'ภูเก็ต', name_en: 'Phuket', region: 'ภาคใต้' },
  { id: '1084', name_th: 'สุราษฎร์ธานี', name_en: 'Surat Thani', region: 'ภาคใต้' },
  { id: '1085', name_th: 'ระนอง', name_en: 'Ranong', region: 'ภาคใต้' },
  { id: '1086', name_th: 'ชุมพร', name_en: 'Chumphon', region: 'ภาคใต้' },
  { id: '1090', name_th: 'สงขลา', name_en: 'Songkhla', region: 'ภาคใต้' },
  { id: '1091', name_th: 'สตูล', name_en: 'Satun', region: 'ภาคใต้' },
  { id: '1092', name_th: 'ตรัง', name_en: 'Trang', region: 'ภาคใต้' },
  { id: '1093', name_th: 'พัทลุง', name_en: 'Phatthalung', region: 'ภาคใต้' },
  { id: '1094', name_th: 'ปัตตานี', name_en: 'Pattani', region: 'ภาคใต้' },
  { id: '1095', name_th: 'ยะลา', name_en: 'Yala', region: 'ภาคใต้' },
  { id: '1096', name_th: 'นราธิวาส', name_en: 'Narathiwat', region: 'ภาคใต้' },
];

export async function seed(knex: Knex): Promise<void> {
  for (const p of PROVINCES) {
    const exists = await knex('provinces').where({ id: p.id }).first('id');
    if (exists) {
      await knex('provinces').where({ id: p.id }).update({
        name_th: p.name_th,
        name_en: p.name_en,
        region: p.region,
      });
    } else {
      await knex('provinces').insert(p);
    }
  }
}
