import type { RolePermissionGrant } from './rbac_matrix_v20260810';

export const RBAC_MATRIX_PRE20260810_ROLE_CODES = [
  'public_anonymous',
  'public_user',
  'factory_operator',
  'diw_central',
  'provincial_office',
  'industrial_estate',
  'monitoring_kpm',
  'monitoring_5_centers',
  'center_director',
  'kpm_director',
  'kwp_director',
  'admin',
] as const;

const ALL = 'ALL' as const;
const PROV = 'IN_PROVINCE' as const;
const EST = 'IN_ESTATE' as const;
const OWN = 'OWN_FACTORY' as const;

export const RBAC_MATRIX_PRE20260810_GRANTS: RolePermissionGrant[] = [
  { role: 'public_anonymous', permission: 'dashboard:view', scope: ALL },
  { role: 'public_anonymous', permission: 'laws:view', scope: null },
  { role: 'public_anonymous', permission: 'faq:view', scope: null },

  { role: 'public_user', permission: 'dashboard:view', scope: ALL },
  { role: 'public_user', permission: 'dashboard.alerts:view', scope: null },
  { role: 'public_user', permission: 'feedback:submit', scope: null },
  { role: 'public_user', permission: 'laws:view', scope: null },
  { role: 'public_user', permission: 'faq:view', scope: null },
  { role: 'public_user', permission: 'chat:ask', scope: null },

  { role: 'factory_operator', permission: 'dashboard:view', scope: OWN },
  { role: 'factory_operator', permission: 'dashboard.alerts:view', scope: null },
  { role: 'factory_operator', permission: 'factories:view', scope: OWN },
  { role: 'factory_operator', permission: 'factories:edit', scope: OWN },
  { role: 'factory_operator', permission: 'cems_wpms_requests:view', scope: OWN },
  { role: 'factory_operator', permission: 'cems_wpms_requests:edit', scope: OWN },
  { role: 'factory_operator', permission: 'kwp_forms:view', scope: OWN },
  { role: 'factory_operator', permission: 'kwp_forms:edit', scope: OWN },
  { role: 'factory_operator', permission: 'bod_cod_errors:view', scope: OWN },
  { role: 'factory_operator', permission: 'bod_cod_errors:edit', scope: OWN },
  { role: 'factory_operator', permission: 'notifications:view', scope: OWN },
  { role: 'factory_operator', permission: 'dashboard.stats:view', scope: OWN },
  { role: 'factory_operator', permission: 'dashboard.stats:export', scope: OWN },
  { role: 'factory_operator', permission: 'helpdesk:submit', scope: null },
  { role: 'factory_operator', permission: 'feedback:submit', scope: null },
  { role: 'factory_operator', permission: 'laws:view', scope: null },
  { role: 'factory_operator', permission: 'faq:view', scope: null },
  { role: 'factory_operator', permission: 'chat:ask', scope: null },

  { role: 'diw_central', permission: 'dashboard:view', scope: ALL },
  { role: 'diw_central', permission: 'dashboard.alerts:view', scope: null },
  { role: 'diw_central', permission: 'dashboard.search:basic', scope: null },
  { role: 'diw_central', permission: 'dashboard.search:advanced', scope: null },
  { role: 'diw_central', permission: 'dashboard.stats:view', scope: ALL },
  { role: 'diw_central', permission: 'dashboard.stats:export', scope: ALL },
  { role: 'diw_central', permission: 'factories:view', scope: ALL },
  { role: 'diw_central', permission: 'kwp_forms:view', scope: ALL },
  { role: 'diw_central', permission: 'bod_cod_errors:view', scope: ALL },
  { role: 'diw_central', permission: 'notifications:view', scope: ALL },
  { role: 'diw_central', permission: 'helpdesk:submit', scope: null },
  { role: 'diw_central', permission: 'feedback:submit', scope: null },
  { role: 'diw_central', permission: 'laws:view', scope: null },
  { role: 'diw_central', permission: 'faq:view', scope: null },
  { role: 'diw_central', permission: 'chat:ask', scope: null },

  { role: 'provincial_office', permission: 'dashboard:view', scope: PROV },
  { role: 'provincial_office', permission: 'dashboard.alerts:view', scope: null },
  { role: 'provincial_office', permission: 'dashboard.search:basic', scope: null },
  { role: 'provincial_office', permission: 'dashboard.search:advanced', scope: null },
  { role: 'provincial_office', permission: 'dashboard.stats:view', scope: PROV },
  { role: 'provincial_office', permission: 'dashboard.stats:export', scope: PROV },
  { role: 'provincial_office', permission: 'factories:view', scope: PROV },
  { role: 'provincial_office', permission: 'kwp_forms:view', scope: PROV },
  { role: 'provincial_office', permission: 'bod_cod_errors:view', scope: PROV },
  { role: 'provincial_office', permission: 'notifications:view', scope: PROV },
  { role: 'provincial_office', permission: 'helpdesk:submit', scope: null },
  { role: 'provincial_office', permission: 'feedback:submit', scope: null },
  { role: 'provincial_office', permission: 'laws:view', scope: null },
  { role: 'provincial_office', permission: 'faq:view', scope: null },
  { role: 'provincial_office', permission: 'chat:ask', scope: null },

  { role: 'industrial_estate', permission: 'dashboard:view', scope: EST },
  { role: 'industrial_estate', permission: 'dashboard.alerts:view', scope: null },
  { role: 'industrial_estate', permission: 'dashboard.search:basic', scope: null },
  { role: 'industrial_estate', permission: 'dashboard.search:advanced', scope: null },
  { role: 'industrial_estate', permission: 'dashboard.stats:view', scope: EST },
  { role: 'industrial_estate', permission: 'dashboard.stats:export', scope: EST },
  { role: 'industrial_estate', permission: 'factories:view', scope: EST },
  { role: 'industrial_estate', permission: 'kwp_forms:view', scope: EST },
  { role: 'industrial_estate', permission: 'bod_cod_errors:view', scope: EST },
  { role: 'industrial_estate', permission: 'notifications:view', scope: EST },
  { role: 'industrial_estate', permission: 'helpdesk:submit', scope: null },
  { role: 'industrial_estate', permission: 'feedback:submit', scope: null },
  { role: 'industrial_estate', permission: 'laws:view', scope: null },
  { role: 'industrial_estate', permission: 'faq:view', scope: null },
  { role: 'industrial_estate', permission: 'chat:ask', scope: null },

  { role: 'monitoring_kpm', permission: 'dashboard:view', scope: ALL },
  { role: 'monitoring_kpm', permission: 'dashboard.alerts:view', scope: null },
  { role: 'monitoring_kpm', permission: 'dashboard.search:basic', scope: null },
  { role: 'monitoring_kpm', permission: 'dashboard.search:advanced', scope: null },
  { role: 'monitoring_kpm', permission: 'dashboard.stats:view', scope: ALL },
  { role: 'monitoring_kpm', permission: 'dashboard.stats:export', scope: ALL },
  { role: 'monitoring_kpm', permission: 'factories:view', scope: ALL },
  { role: 'monitoring_kpm', permission: 'factories:edit', scope: ALL },
  { role: 'monitoring_kpm', permission: 'factories:approve', scope: ALL },
  { role: 'monitoring_kpm', permission: 'cems_wpms_requests:view', scope: ALL },
  { role: 'monitoring_kpm', permission: 'cems_wpms_requests:edit', scope: ALL },
  { role: 'monitoring_kpm', permission: 'cems_wpms_requests:approve', scope: ALL },
  { role: 'monitoring_kpm', permission: 'cems_wpms_requests:direct_connect', scope: ALL },
  { role: 'monitoring_kpm', permission: 'kwp_forms:view', scope: ALL },
  { role: 'monitoring_kpm', permission: 'kwp_forms:edit', scope: ALL },
  { role: 'monitoring_kpm', permission: 'kwp_forms:approve', scope: ALL },
  { role: 'monitoring_kpm', permission: 'bod_cod_errors:view', scope: ALL },
  { role: 'monitoring_kpm', permission: 'bod_cod_errors:edit', scope: ALL },
  { role: 'monitoring_kpm', permission: 'bod_cod_errors:approve', scope: ALL },
  { role: 'monitoring_kpm', permission: 'notifications:view', scope: ALL },
  { role: 'monitoring_kpm', permission: 'helpdesk:submit', scope: null },
  { role: 'monitoring_kpm', permission: 'feedback:submit', scope: null },
  { role: 'monitoring_kpm', permission: 'laws:view', scope: null },
  { role: 'monitoring_kpm', permission: 'faq:view', scope: null },
  { role: 'monitoring_kpm', permission: 'chat:ask', scope: null },
  { role: 'monitoring_kpm', permission: 'chat:answer', scope: null },

  { role: 'monitoring_5_centers', permission: 'dashboard:view', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'dashboard.alerts:view', scope: null },
  { role: 'monitoring_5_centers', permission: 'dashboard.search:basic', scope: null },
  { role: 'monitoring_5_centers', permission: 'dashboard.search:advanced', scope: null },
  { role: 'monitoring_5_centers', permission: 'dashboard.stats:view', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'dashboard.stats:export', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'factories:view', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'factories:edit', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'factories:approve', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'cems_wpms_requests:view', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'kwp_forms:view', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'kwp_forms:edit', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'kwp_forms:approve', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'bod_cod_errors:view', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'bod_cod_errors:edit', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'bod_cod_errors:approve', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'notifications:view', scope: ALL },
  { role: 'monitoring_5_centers', permission: 'helpdesk:submit', scope: null },
  { role: 'monitoring_5_centers', permission: 'feedback:submit', scope: null },
  { role: 'monitoring_5_centers', permission: 'laws:view', scope: null },
  { role: 'monitoring_5_centers', permission: 'faq:view', scope: null },
  { role: 'monitoring_5_centers', permission: 'chat:ask', scope: null },
  { role: 'monitoring_5_centers', permission: 'chat:answer', scope: null },

  ...(['center_director', 'kpm_director', 'kwp_director'] as const).flatMap((role) => [
    { role, permission: 'dashboard:view', scope: ALL },
    { role, permission: 'dashboard.alerts:view', scope: null },
    { role, permission: 'dashboard.search:basic', scope: null },
    { role, permission: 'dashboard.search:advanced', scope: null },
    { role, permission: 'dashboard.stats:view', scope: ALL },
    { role, permission: 'dashboard.stats:export', scope: ALL },
    { role, permission: 'factories:view', scope: ALL },
    { role, permission: 'cems_wpms_requests:view', scope: ALL },
    { role, permission: 'kwp_forms:view', scope: ALL },
    { role, permission: 'bod_cod_errors:view', scope: ALL },
    { role, permission: 'notifications:view', scope: ALL },
    { role, permission: 'helpdesk:submit', scope: null },
    { role, permission: 'feedback:submit', scope: null },
    { role, permission: 'laws:view', scope: null },
    { role, permission: 'faq:view', scope: null },
    { role, permission: 'chat:ask', scope: null },
  ]),

  ...([
    'dashboard:view',
    'dashboard.alerts:view',
    'dashboard.search:basic',
    'dashboard.search:advanced',
    'dashboard.stats:view',
    'dashboard.stats:export',
    'factories:view',
    'factories:edit',
    'factories:approve',
    'cems_wpms_requests:view',
    'cems_wpms_requests:edit',
    'cems_wpms_requests:approve',
    'cems_wpms_requests:direct_connect',
    'kwp_forms:view',
    'kwp_forms:edit',
    'kwp_forms:approve',
    'bod_cod_errors:view',
    'bod_cod_errors:edit',
    'bod_cod_errors:approve',
    'notifications:view',
    'notifications:view_status',
    'notifications:edit',
    'notifications:approve',
    'helpdesk:submit',
    'feedback:submit',
    'laws:view',
    'laws:edit',
    'faq:view',
    'faq:edit',
    'chat:answer',
    'eligible_factories:manage',
    'api_documentation:view',
    'users:view',
    'users:edit',
    'roles:view',
    'roles:edit',
    'audit:view',
  ] as const).map((permission) => ({
    role: 'admin',
    permission,
    scope:
      permission === 'dashboard.alerts:view' ||
      permission === 'dashboard.search:basic' ||
      permission === 'dashboard.search:advanced' ||
      permission === 'notifications:view_status' ||
      permission === 'helpdesk:submit' ||
      permission === 'feedback:submit' ||
      permission === 'laws:view' ||
      permission === 'laws:edit' ||
      permission === 'faq:view' ||
      permission === 'faq:edit' ||
      permission === 'chat:answer'
        ? null
        : ALL,
  })),
];
